version: "3"
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.prd
    volumes:
      - .:/app/api
    ports:
      - 3001:3001
    depends_on:
      - db
    tty: true
    stdin_open: true
    restart: always
  db:
    image: mysql:5.7
    # DBのレコードが日本語だと文字化けするので、utf8をセットする
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
      - db-volume:/var/lib/mysql
    # 環境変数
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: "Asia/Tokyo"
    ports:
      - "3306:3306"
    restart: always
# PC上にdb-volumeという名前でボリューム（データ領域）が作成される
# コンテナを作り直したとしてもPC上に残るようにするために設定
volumes:
  db-volume:
